version: '3'
services:

# Create a PostgreSQL database
  database:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codeconnectdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: always
    networks:
      - codeconnect

# Build from the Dockerfile in the server directory
  server:
    build: ./server
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      database:
        condition: service_healthy
    networks:
      - codeconnect

# Build from the Dockerfile in the client directory
  client:
    build: ./client
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - server
    networks:
      - codeconnect

# Create a network for the services to communicate
networks:
  codeconnect:
    driver: bridge
