version: '3'
services:

# Create a PostgreSQL database
  database:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codeconnectdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

# Build from the Dockerfile in the client directory
  # client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"

# Build from the Dockerfile in the server directory
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
